interface MCPItem { name: string; description: string; slug: string }
interface SkillItem { name: string; file_name: string }
interface RuleItem { name: string; file_name: string }

export function generateClaudeMd(
  projectName: string,
  platform: string,
  mcps: MCPItem[],
  skills: SkillItem[],
  rules: RuleItem[],
): string {
  const lines: string[] = [
    `# ${projectName}`,
    '',
    '## Project Setup',
    '',
    `**Platform:** ${platform}`,
    '',
  ]

  if (mcps.length > 0) {
    lines.push('## MCP Servers', '')
    for (const mcp of mcps) {
      lines.push(`- **${mcp.name}**: ${mcp.description}`)
    }
    lines.push('')
  }

  if (skills.length > 0) {
    lines.push('## Skills', '')
    for (const skill of skills) {
      lines.push(`- \`skills/${skill.file_name}\``)
    }
    lines.push('')
  }

  if (rules.length > 0) {
    lines.push('## Rules', '')
    for (const rule of rules) {
      lines.push(`- \`rules/${rule.file_name}\``)
    }
    lines.push('')
  }

  lines.push(
    '## Notes',
    '',
    `> Generated by [FlowBase Studio](https://flowbase.studio) — The Visual Workspace for Claude Code.`,
    '',
  )

  return lines.join('\n')
}
